import type { InstitutionGroup } from "@/types/financial-institution"

export const institutionGroups: InstitutionGroup[] = [
  {
    id: "major-national",
    title: "Major National Banks",
    institutions: [
      { id: "chase", name: "Chase", category: "major-national" },
      { id: "bank-of-america", name: "Bank of America", category: "major-national" },
      { id: "wells-fargo", name: "Wells Fargo", category: "major-national" },
      { id: "citibank", name: "Citibank", category: "major-national" },
      { id: "us-bank", name: "U.S. Bank", category: "major-national" },
      { id: "pnc", name: "PNC Bank", category: "major-national" },
      { id: "truist", name: "Truist Bank", category: "major-national" },
      { id: "capital-one", name: "Capital One", category: "major-national" },
    ],
  },
  {
    id: "online-only",
    title: "Online-Only Banks & Neobanks",
    institutions: [
      { id: "ally", name: "Ally Bank", category: "online-only" },
      { id: "chime", name: "Chime", category: "online-only" },
      { id: "sofi", name: "SoFi", category: "online-only" },
      { id: "marcus", name: "Marcus by Goldman Sachs", category: "online-only" },
      { id: "discover-bank", name: "Discover Bank", category: "online-only" },
      { id: "varo", name: "Varo Bank", category: "online-only" },
      { id: "current", name: "Current", category: "online-only" },
      { id: "aspiration", name: "Aspiration", category: "online-only" },
    ],
  },
  {
    id: "regional",
    title: "Regional Banks",
    institutions: [
      { id: "regions", name: "Regions Bank", category: "regional" },
      { id: "fifth-third", name: "Fifth Third Bank", category: "regional" },
      { id: "keybank", name: "KeyBank", category: "regional" },
      { id: "huntington", name: "Huntington Bank", category: "regional" },
      { id: "mt-bank", name: "M&T Bank", category: "regional" },
      { id: "citizens", name: "Citizens Bank", category: "regional" },
      { id: "td-bank-us", name: "TD Bank (US)", category: "regional" },
      { id: "bmo-harris", name: "BMO Harris", category: "regional" },
      { id: "comerica", name: "Comerica Bank", category: "regional" },
      { id: "zions", name: "Zions Bancorporation", category: "regional" },
      { id: "synovus", name: "Synovus Bank", category: "regional" },
      { id: "first-horizon", name: "First Horizon Bank", category: "regional" },
    ],
  },
  {
    id: "credit-unions",
    title: "Credit Unions",
    institutions: [
      { id: "navy-federal", name: "Navy Federal Credit Union", category: "credit-unions" },
      { id: "pentagon-federal", name: "Pentagon Federal (PenFed)", category: "credit-unions" },
      { id: "schools-first", name: "SchoolsFirst FCU", category: "credit-unions" },
      { id: "golden-1", name: "Golden 1 Credit Union", category: "credit-unions" },
      { id: "alliant", name: "Alliant Credit Union", category: "credit-unions" },
      { id: "star-one", name: "Star One Credit Union", category: "credit-unions" },
      { id: "america-first", name: "America First Credit Union", category: "credit-unions" },
      { id: "becu", name: "BECU", category: "credit-unions" },
      { id: "suncoast", name: "Suncoast Credit Union", category: "credit-unions" },
      { id: "digital-fcu", name: "Digital Federal Credit Union", category: "credit-unions" },
      { id: "first-tech", name: "First Tech Federal Credit Union", category: "credit-unions" },
      { id: "security-service", name: "Security Service FCU", category: "credit-unions" },
    ],
  },
  {
    id: "digital-hybrid",
    title: "Digital & Hybrid Banks",
    institutions: [
      { id: "axos", name: "Axos Bank", category: "digital-hybrid" },
      { id: "cit-bank", name: "CIT Bank", category: "digital-hybrid" },
      { id: "synchrony", name: "Synchrony Bank", category: "digital-hybrid" },
      { id: "webbank", name: "WebBank", category: "digital-hybrid" },
      { id: "quontic", name: "Quontic Bank", category: "digital-hybrid" },
      { id: "nbkc", name: "nbkc bank", category: "digital-hybrid" },
      { id: "live-oak", name: "Live Oak Bank", category: "digital-hybrid" },
      { id: "cross-river", name: "Cross River Bank", category: "digital-hybrid" },
      { id: "patriot-bank", name: "Patriot Bank", category: "digital-hybrid" },
    ],
  },
]
