import type { InstitutionGroup } from "@/types/financial-institution"

export const institutionGroups: InstitutionGroup[] = [
  {
    id: "big-6",
    title: "The Big 6 Banks",
    institutions: [
      { id: "rbc", name: "Royal Bank of Canada (RBC)", category: "big-6" },
      { id: "td", name: "TD Bank", category: "big-6" },
      { id: "scotiabank", name: "Scotiabank", category: "big-6" },
      { id: "bmo", name: "BMO", category: "big-6" },
      { id: "cibc", name: "CIBC", category: "big-6" },
      { id: "national", name: "National Bank", category: "big-6" },
    ],
  },
  {
    id: "online-only",
    title: "Online-Only Banks & Neobanks",
    institutions: [
      { id: "tangerine", name: "Tangerine", category: "online-only" },
      { id: "simplii", name: "Simplii", category: "online-only" },
      { id: "eq-bank", name: "EQ Bank", category: "online-only" },
      { id: "motive", name: "Motive Financial", category: "online-only" },
      { id: "wealthsimple-cash", name: "Wealthsimple Cash", category: "online-only" },
      { id: "koho", name: "Koho", category: "online-only" },
      { id: "mogo", name: "Mogo", category: "online-only" },
      { id: "neo", name: "Neo Financial", category: "online-only" },
    ],
  },
  {
    id: "schedule-i-ii",
    title: "Canadian Schedule I & II Banks",
    institutions: [
      { id: "cwb", name: "Canadian Western Bank", category: "schedule-i-ii" },
      { id: "laurentian", name: "Laurentian Bank", category: "schedule-i-ii" },
      { id: "hsbc", name: "HSBC Canada", category: "schedule-i-ii" },
      { id: "manulife", name: "Manulife Bank", category: "schedule-i-ii" },
      { id: "firstontario", name: "FirstOntario CU", category: "schedule-i-ii" },
      { id: "atb", name: "ATB Financial", category: "schedule-i-ii" },
      { id: "bridgewater", name: "Bridgewater Bank", category: "schedule-i-ii" },
      { id: "concentra", name: "Concentra Bank", category: "schedule-i-ii" },
      { id: "icici", name: "ICICI Canada", category: "schedule-i-ii" },
      { id: "habib", name: "Habib Bank", category: "schedule-i-ii" },
      { id: "citibank", name: "Citibank Canada", category: "schedule-i-ii" },
      { id: "pc-financial", name: "President's Choice Financial", category: "schedule-i-ii" },
      { id: "peoples-trust", name: "Peoples Trust", category: "schedule-i-ii" },
    ],
  },
  {
    id: "credit-unions",
    title: "Credit Unions",
    institutions: [
      { id: "desjardins", name: "Desjardins", category: "credit-unions" },
      { id: "coast-capital", name: "Coast Capital", category: "credit-unions" },
      { id: "vancity", name: "Vancity", category: "credit-unions" },
      { id: "meridian", name: "Meridian", category: "credit-unions" },
      { id: "alterna", name: "Alterna Savings", category: "credit-unions" },
      { id: "duca", name: "DUCA", category: "credit-unions" },
      { id: "servus", name: "Servus", category: "credit-unions" },
      { id: "affinity", name: "Affinity", category: "credit-unions" },
      { id: "first-west", name: "First West", category: "credit-unions" },
      { id: "steinbach", name: "Steinbach", category: "credit-unions" },
      { id: "libro", name: "Libro", category: "credit-unions" },
      { id: "conexus", name: "Conexus", category: "credit-unions" },
      { id: "prospera", name: "Prospera", category: "credit-unions" },
      { id: "uni", name: "Uni Financial", category: "credit-unions" },
      { id: "blueshore", name: "BlueShore", category: "credit-unions" },
      { id: "kawartha", name: "Kawartha", category: "credit-unions" },
      { id: "innovation", name: "Innovation FCU", category: "credit-unions" },
      { id: "kindred", name: "Kindred", category: "credit-unions" },
      { id: "interior", name: "Interior Savings", category: "credit-unions" },
    ],
  },
  {
    id: "digital-hybrid",
    title: "Smaller Digital & Hybrid Banks",
    institutions: [
      { id: "wealthone", name: "WealthOne", category: "digital-hybrid" },
      { id: "oaken", name: "Oaken", category: "digital-hybrid" },
      { id: "alterna-bank", name: "Alterna Bank", category: "digital-hybrid" },
      { id: "motusbank", name: "Motusbank", category: "digital-hybrid" },
      { id: "achieva", name: "Achieva", category: "digital-hybrid" },
      { id: "outlook", name: "Outlook", category: "digital-hybrid" },
      { id: "implicity", name: "Implicity", category: "digital-hybrid" },
      { id: "hubert", name: "Hubert", category: "digital-hybrid" },
      { id: "maxa", name: "MAXA", category: "digital-hybrid" },
    ],
  },
]
